config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("categories/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search", resolve_search, name="search")
]

movies/urls.py
from django.urls import path
from movies.views import MoviesView, MovieDetail, CreateMovie, UpdateMovie

app_name="movies"

urlpatterns = [
  path("", MoviesView.as_view(), name="movies"),
  path("<int:pk>", MovieDetail.as_view(), name="movie"),
  path("<int:pk>/update", UpdateMovie.as_view(), name="update"),
  path("create", CreateMovie.as_view(), name="create"),
]

reviews/urls.py
from django.urls import path
from . import views


app_name = "reviews"

urlpatterns = [
  path("create/<int:pk>", views.create_review, name="create"),
  path("delete/<int:pk>", views.DeleteReview.as_view(), name="delete"),
  ]

movies/models.py
from django.urls import reverse
from django.db import models
from core.models import CoreModel


class Movie(CoreModel):
    """ Movie Model """

    title = models.CharField(max_length=120)
    year = models.IntegerField()
    cover_image = models.ImageField(null=True, blank=True)
    rating = models.FloatField()
    category = models.ForeignKey(
        "categories.Category", on_delete=models.CASCADE, related_name="movies")
    director = models.ForeignKey(
        "people.Person", on_delete=models.CASCADE, related_name="movies")
    cast = models.ManyToManyField("people.Person")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movies:movie", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["-created_at"]

movies/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from movies.models import Movie
from reviews import forms
from django.shortcuts import render


class MoviesView(ListView):

    model = Movie
    paginate_by = 15
    paginate_orphans = 5
    ordering = "-created_at"
    context_object_name = "movies"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "All Movies"
        return context


class MovieDetail(DetailView):
  model = Movie
  context_object_name = 'movie'
  def get(self, *args, **kwargs):
    pk = kwargs.get("pk")
    movie = Movie.objects.get_or_none(pk=pk)
    form = forms.CreateReviewForm()
    return render(
        self.request,
        "movies/movie_detail.html",
        {"movie":movie, "form": form},
    )


class CreateMovie(CreateView):
    model = Movie
    fields = (
        "title",
        "year",
        "cover_image",
        "rating",
        "category",
        "director",
        "cast",
    )


class UpdateMovie(UpdateView):
    model = Movie
    fields = (
        "title",
        "year",
        "cover_image",
        "rating",
        "category",
        "director",
        "cast",
    )

templates/movies/movie_detail.html
{% extends "base.html" %}

{% block page_title %}
  {{movie.title}}
{% endblock page_title %}

{% block content %}

<div class="flex flex-col items-center bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
  <h2 class="font-bold">{{movie.title}}</h2>
  <div class="flex items-center my-2">
    <div class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700">{{movie.year}}</div>
    <div class="bg-orange-400 text-white px-3 shadow-md py-1 rounded-full mx-4">{{movie.category}}</div>
  </div>
  <div class="my-2">Director:
    <div class="inline-block bg-white shadow-md rounded-full px-3 py-1 text-sm font-semibold text-gray-700">{{movie.director}}</div>
  </div>
  <div class="my-2">Cast: {% for i in movie.cast.all %} 
    <div class="inline-block bg-white shadow-md rounded-full px-3 py-1 text-sm font-semibold text-gray-700">{{i}}</div> {% endfor %}
  </div>
  <div class="flex">
    <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold mt-4 py-2 px-4 rounded" href="{% url 'movies:update' movie.pk %}">Edit Movie</a>
    {% if user.is_authenticated %}
      {% include "mixins/fav_button.html" with obj=movie kind='movie' %}
    {% endif %}
  </div>
  <div class="mt-10 w-1/2">
    <h4 class="font-medium text-2xl mb-2 text-center  text-gray-700">Reviews</h4>
    <div class="flex items-center justify-center">
        <div class="flex items-center">
            <i class="fas fa-star text-yellow-500"></i>
            <span class="font-bold text-xl ml-2">{{movie.rating}}</span>
        </div>
        <div class="h-4 w-px bg-gray-400 mx-5"></div>
        <div>
            <span class="font-bold text-xl mr-1">{{movie.reviews.count}}</span>
            <span>review{{movie.reviews.count|pluralize}}</span>
        </div>
    </div>
    <div class="mt-10">
      {% for review in movie.reviews.all  %}
      <div class="border-section">
          <div class="mb-3 flex">
            <div class="flex flex-col mr-3 flex-0">
                <span class="font-medium">{{review.created_by.username}}</span>
                <span class="text-sm text-gray-500">{{review.created_at|date:'m/d'}}</span>
            </div>
            <div class="text-gray-700 mr-5 flex-0"><i class="fas fa-star text-yellow-500 text-xs mr-1"></i>{{review.rating}}</div>
            <div class="flex-1">
              <p>{{review.text}}</p>
              {% if review.created_by == user %}
              <a class="bg-red-400 hover:bg-red-600 text-white font-semibold text-sm py-1 px-2 rounded" href="{% url 'reviews:delete' review.pk %}">Delete</a>
              {% endif %}
            </div>
          </div>
      </div>
      {% endfor %}    
    </div>
  </div>
  <div class="py-10">
    {% if user.is_authenticated %}
    <form action="{% url 'reviews:create' movie.pk %}?kind=movie" method="POST" mx-auto">
        {% csrf_token %}
        {% for field in form %}
          <div class="mb-3">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="{{field.auto_id}}">{{field.label}}</label>
            <div class="shadow appearance-none border rounded w-full text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
              {{field}}
            </div>
          </div>
        {% endfor %}
        <button class="btn-link bg-orange-400 hover:bg-orange-600 text-white font-bold w-full py-2 px-4 rounded">Submit Review</button>
    </form>
    {% endif %}
  </div>
</div>
{% endblock content %}

templates/movies/movie_form.html
{% extends "base.html" %}

{% block page_title %}
  Movie
{% endblock page_title %}

{% block content %}

  {% include 'mixins/form.html' with form=form cta="Save" %}

{% endblock content %}

templates/movies/movie_list.html
{% extends "base.html" %}

{% block page_title %}
  Movies
{% endblock page_title %}

{% block content %}
<div class="px-5">
  <h2 class="ml-1 text-3xl text-blue-600">Movies</h2>
  <div class="grid my-5 grid-cols-4 gap-5">
	{% for movie in movies %}
    {% include "mixins/movie.html" with movie=movie %}
	{% endfor %}
  </div>
<hr />
</div>
<div class="mt-2 flex justify-center">
  <div>
  {% if page_obj.has_previous %}
        <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold py-1 px-2 rounded" href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}

    <span class="font-bold text-blue-600">
    Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
    </span>

    {% if page_obj.has_next  %}
        <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold py-1 px-2 rounded" href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}
  </div>
</div>
{% endblock content %}